server:
  port: 7443
  ssl:
    enabled: true
    key-alias: server
    key-store: classpath:my-keystore.jks
    key-store-password: storepass123
    key-store-type: jks
    trust-store: classpath:my-truststore.jks
    trust-store-password: storepass123
    client-auth: need
