server:
  port: 7443
  ssl:
    enabled: true
    key-alias: mtls-sample
    key-store: classpath:mtls-keystore.jks
    key-store-password: storepass123
    key-store-type: jks
    trust-store: classpath:mtls-truststore.jks
    trust-store-password: storepass123
    client-auth: need
