server:
  port: 9443
  ssl:
    enabled: true
    key-alias: mtls-sample
    key-store: classpath:mtls-keystore.jks
    key-store-password: storepass123
    key-store-type: jks
client:
  ssl:
    key-store: classpath:mtls-keystore.jks
    key-password: storepass123
    key-store-password: storepass123
    trust-store: classpath:mtls-truststore.jks
    trust-store-password: storepass123